Config = {
    ExcludeDrop = {
        'Exiting',
        'Disconnected',
        'cup-leopard-triple',
        'Kicked',
        'Banned'
    },
    Settings = {
        QueueDelay = 1,
        MaxTimeBoost = 10,
        Grace = 5
    }
}

Config.Strings = {
    Add = 'Added %s (SID: %s, Identifier: %s) To Queue %s/%s',
    Banned = 'You\'re Banned, Appeal At https://blueskyrp.com\n\nReason: %s\nExpires: %s\nID: %s',
    Checking = 'Checking Whitelist Status',
    DatabaseWait = 'Waiting For Server To Be Ready, Please Wait (%s - %s - %s)\n\nIf The Emotes Stop Changing, Please Reconnect',
    Disconnected = '%s (SID: %s, Identifier: %s) Disconnected, Starting Grace',
    Dropped = 'Dropped From Server.',
	Dropping = '^8Dropping Lowest Priority Player For Privileged Player %s',
	Grace = '^5Starting Grace Timer For %s - Ends At %s^7',
    IdentifierNotLinked = 'Identifier Not Linked To Any Blue Sky Account, Please Go To https://blueskyrp.com/ & Link Your Account.',
    Joined = '%s (SID: %s, Identifier: %s) Joined The Server',
    Joining = 'Joining Server...',
    NoAccountData = 'Unable To Get Your Account Data, Please Try Again.',
    NoLicense = 'No License Identifier, Please Relaunch FiveM. Contact FiveM Support If This Continues',
    NotWhitelisted = 'Not Whitelisted - Apply Today At https://blueskyrp.com/',
    PermaBanned = 'Permanently Banned, Appeal At https://blueskyrp.com/\n\nReason: %s\nID: %s',
	PrioAdd = 'Added %s (%s) To Queue %s/%s With Priority %s',
    PrioWaiting = 'Waiting For Priority Player To Join Server',
	Queued = 'Position %s of %s - Time In Queue: %s%s',
	Retrieving = 'Retrieving Queue Information',
	Waiting = 'Waiting For Queue To Open - %s Seconds'
}

Config.Emotes = {
    '🍕',
    '🍔',
    '🍟',
    '🌭',
    '🍿',
    '🥓',
    '🥚',
    '🍳',
    '🧇',
    '🥞',
    '🧈',
    '🍞',
    '🥐',
    '🥨',
    '🥯',
    '🥖',
    '🧀',
    '🥗',
    '🥙',
    '🥪',
    '🌮',
    '🌮',
    '🌯',
    '🥫',
    '🍖',
    '🍗',
    '🥩',
    '🍠',
    '🥟',
    '🥠',
    '🥡',
    '🍱',
    '🍘',
    '🍙',
    '🍚',
    '🍛',
    '🍜',
    '🦪',
    '🦪',
    '🍣',
    '🍤',
    '🍥',
    '🥮',
    '🍢',
    '🧆',
    '🥘',
    '🍲',
    '🍝',
    '🥣',
    '🥧',
    '🍦',
    '🍧',
    '🍨',
    '🍩',
    '🍪',
    '🎂',
    '🍰',
    '🧁',
    '🍫',
    '🍬',
    '🍭',
    '🍡',
    '🍮',
    '🍯',
    '🍼'
}